---
- hostname:
    name: osmc

- name: Update apt repo
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: Upgrade apt packages
  apt: upgrade=dist
  environment:
    PATH: /usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin

- name: Basic packages and configs
  action: apt pkg={{ item }} state=present
  with_items:
    - htop
    - sysstat
    - vim
    - nmap
    - rsync
    - avahi-daemon
    - watchdog
  environment:
    PATH: /usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
