---
- name: Restart deluged
  service:
    name: deluged
    state: restarted
    enabled: yes

- name: Set config allow remote
  shell: "deluge-console 'config -s allow_remote True'"

- name: Set config download location
  shell: "deluge-console 'config -s download_location /home/osmc/Downloads'"

- name: Update service for deluge-web
  shell: "update-rc.d deluge-web defaults"

- name: Restart deluge-web
  service:
    name: deluge-web
    state: restarted
    enabled: yes
